# .travis.yml
language: node_js   #前端工程所以是JavaScript，编译环境是node_js
node_js: stable

# 邮件通知构建结果
notifications:
  email:
    recipients:
      - Mr_daijc@163.com
    on_success: never # default: change
    on_failure: always # default: always

branchs:
  only:
  - master  #指定只有检测到master分支有变动时才执行任务

# Travis-CI Caching
cache:
  yarn: true
  directories:
    - node_modules    # 缓存 node_js 依赖，提升第二次构建的效率

# S: Build Lifecycle
install:
  - yarn

# 无其他依赖项所以执行npm run build 构建就行了
script:
  - yarn run build